name: Build Windows Portable

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.*'
        modules: 'all'
        cache: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Add msvc-dev-cmd
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: Build Sioyek (portable)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build_windows.bat portable

    - name: Upload Windows portable artifact
      uses: actions/upload-artifact@v7
      with:
        path: sioyek-release-windows-portable.zip
        archive: false
        retention-days: 7
